[book]
authors = ["Team B12"]
language = "en"
multilingual = false
src = "src"
title = "How we AI"

[output.html]
git-repository-url = "https://github.com/b12io/how-we-ai/tree/main"
edit-url-template = "https://github.com/b12io/how-we-ai/edit/main/{path}"